# smash together the variables returned by lm, summary, and anova
lm.combo = function(formula, data, subset) {
  d = data[subset,]
  mod = lm(formula=formula, data=d)
  summ = summary(mod)
  for (name in names(summ)) { 
    mod[[name]] = summ[[name]]
  }
  mod$anova = anova(mod)
  mod
}

getHSDRow = function(x, facCombo1, facCombo2) {
  try1 = paste(facCombo1,facCombo2, sep="-")
  message(try1)
  try2 = paste(facCombo2,facCombo1, sep="-")
  message(try2)
  row1 = as.data.frame(x)[try1,]
  row2 = as.data.frame(x)[try2,]
  row1[is.na(row1)] <- 0
  row2[is.na(row2)] <- 0
  final = row1 + row2
  rownames(final) <- try1
  final
}

dunn <- function(data, levels, method="bh", alpha=.05, altp = T)
{
  # Run the dunn test on data, split by levels, and add a table to the default output
  # that includes medians of each group and the result of multcompLetters.
  # 
  # The current flow assumes that input has had the ":" replaced by ", ", and will reverse
  # that string replace when necessary. This is important to get multcompLetters to parse the 
  # pairwise comparisons correctly.
  # defaults -
  # altp- affects the output format generated by dunnTest, but not the outcome of the test
  # alpha- is passed to dunnTest, but the unthresholded adjusted p-values are evaluated
  # when passed to multcompLetters 
  # 
  meds = lapply(split(data, factor(levels)), function(x) {median(x, na.rm=T)}) %>% dplyr::bind_rows()
  
  dunn.out=dunnTest(data, levels, method=method, alpha=alpha, altp=altp)
  
  # Record P.adj and properly format names
  comp.c = dunn.out$res %>% pull(P.adj)
  names(comp.c) <- dunn.out$res %>% pull(Comparison) %>% str_replace_all(", ", ":") %>% str_replace_all(" - ", "-")
  
  # multcompLetters
  letts = multcompLetters(comp.c <= alpha)$Letters
  names(letts) <- names(letts) %>% str_replace_all(":",", ")
  dunn.out$multCompLetters = data.frame(median=t(meds[names(letts)]), # indexing by name in case the lapply output is in a different order
                                        multCompLetter=letts)
  dunn.out
}
